### ISSUE TITLE
splunk_cf.yaml doesn't configure public IP address

### ISSUE THREAD

**Issue by ckamps** [aws-samples/aws-emr-eks-log-forwarding#1]
I noticed that the output value for `SplunkPublicDns` was empty when I created a stack using the template. I modified the template to explicitly call for associating a public IP address as shown in the following code snippet:

```
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      KeyName: !Ref KeyName
      ImageId: !Ref LatestAmiId
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet: [!Ref InstanceSecurityGroup]
          SubnetId: !Ref PublicSubnet0
...
```
